#!/usr/bin/env bash
# Transfers a file from my client to a server.
# Accepts four arguments:
#    1. The path to the file to be transferred.
#    2. The IP of the server to transfer the file to.
#    3. The username that scp connects with.
#    4. The path to the SSH private key that scp uses.

if [ $# -lt 3 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
