#!/usr/bin/env bash
# Installs and setup haproxy

# apt-get install -y software-properties-common
# add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get install -y haproxy # =1.8.\*
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.default
# echo "ENABLED=1" > /etc/default/haproxy

# Listen to web1 and web2 servers                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 325990-web-01	34.207.64.86 check
   server 325990-web-02	54.158.217.146 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
