#!/usr/bin/env bash
# Nginx likes port 80

sudo apt-get update -y
sudo apt-get install nginx

sudo service nginx restart

sed -i 's/^\s*listen\s*.*$/    listen 80;'/ /etc/nginx/nginx.conf

sudo service nginx restart
