#!/usr/bin/env bash
# Nginx likes port 80 - make an nginx server listen on port 80
sudo apt-get update -y
sudo apt-get install nginx -y
ufw allow 'Nginx HTTP'
# sudo sed -i 's/^\s*listen\s*.*$/    listen 80 default_server;/' /etc/nginx/sites-available/default
# sudo sed -i 's/^\s*listen [::].*$/    listen [::]:80 default_server;/' /etc/nginx/sites-available/default
# sudo sed -i 's/^\s*listen\s*.*$/    listen 80;/' /etc/nginx/nginx.conf
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
