#!/usr/bin/env bash
# Run Nginx as Nginx
chmod 644 /etc/nginx/nginx.conf
sudo sed -i "s/^#user .*/user nginx nginx/" /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
