#!/usr/bin/env bash
# 7 lines or less - Run Nginx as Nginx
sudo sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
