#!/usr/bin/env bash
# 7 lines or less -  Run Nginx as Ngin

sudo sed -i "s/^user .*/user nginx nginx;/" /etc/nginx/nginx.conf
sudo sed -i "s/^    listen .*/    listen 8080;/" /etc/nginx/nginx.conf
sudo sed -i "s/^    server_name .*/    server_name _;/" /etc/nginx/nginx.conf
sudo service nginx restart
